name: CI/CD Desktop App

on:
  push:
    tags:
     - 'v*.*.*'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Desktop App
        run: |
          cd desktop-app
          npm install
          npm run release-linux
          rm -Rf ./release/linux-unpacked
          rm -Rf ./release/.cache
          rm -Rf ./release/builder-debug.yml
          rm -Rf ./release/builder-effective-config.yaml
          cp -r ./release/ ./temp/

      - name: Move to Temp
        run: |
          cd desktop-app/temp
          ls

