name: CI/CD Desktop App

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  S3_BUCKET: s3://noovolari-leapp-website-distribution-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Desktop App
        run: |
          cd desktop-app
          NEW_PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          TAG_VERSION=${GITHUB_REF#refs/*/}
          echo $NEW_PACKAGE_VERSION
          echo $TAG_VERSION
          echo ${{ env.S3_BUCKET }}


      - name: Move to Temp
        run: |
          ls
